### PR TITLE
Update link to the stable lein

### PR DESCRIPTION
**Pull request by maxprokopiev**
Hi guys!
I've noticed that this cookbook provides an outdated version of `bin/lein`.
Why don't you fetch from https://raw.github.com/technomancy/leiningen/stable/bin/lein?

### CODE REVIEW

**Comment by aiman-alsari** [comment]
Hi, I would greatly appreciate this being merged ASAP. In the last few days the S3 link that was previously working is now giving a 403.

**Comment by oneness** [comment]
Merging now.  I'd like someone take ownership of this project since we are not actively maintaining/contributing to it. Any volunteers?

**Comment by maxprokopiev** [comment]
@oneness I can do that (you can email me all the details)

**Comment by maxprokopiev** [comment]
@oneness and many thanks for merging this one, btw :+1:

**Comment by oneness** [comment]
I just sent you an invite to have admin rights to this repo. Let me know if it does not.

**Comment by aiman-alsari** [comment]
Thanks guys, @maxprokopiev you'll also need to merge in @rchekaluk fix for issue #5

**Comment by aiman-alsari** [comment]
@maxprokopiev I've also noticed that the one on the chef supermarket has a link that points here but is actually a different leiningen cookbook altogether (https://github.com/henrygarner/leiningen)

**Pull request merged**
